import type { Metadata } from "next";
import { Inter } from 'next/font/google'
import "./globals.css";
import { Footer } from "@/components/Footer";

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${inter.className} antialiased flex flex-col h-screen items-center`}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
